import LegalLayout from '../components/legal/LegalLayout';

const TOC = [
  { id: 'sec-1', num: '1.0', title: 'Preliminary Recitals & Statutory Enforceability' },
  { id: 'sec-2', num: '2.0', title: 'Statutory Definitions & Construction' },
  { id: 'sec-3', num: '3.0', title: 'Entity Identification & Regulatory Status' },
  { id: 'sec-4', num: '4.0', title: 'User Eligibility, Accounts & Contractual Capacity' },
  { id: 'sec-5', num: '5.0', title: 'Made-to-Order Manufacturing Doctrine & Tolerances' },
  { id: 'sec-6', num: '6.0', title: 'Order Offer, Acceptance & Strict No-Cancellation Covenant' },
  { id: 'sec-7', num: '7.0', title: 'Pricing, Currency (INR) & Tax Invoicing (GST)' },
  { id: 'sec-8', num: '8.0', title: 'Online Payment Protocols & Non-Retention of Credentials' },
  { id: 'sec-9', num: '9.0', title: 'Domestic Shipping, Delivery Timelines & Risk Allocation' },
  { id: 'sec-10', num: '10.0', title: 'Returns, Inspection & Qualifying Defect Policy' },
  { id: 'sec-11', num: '11.0', title: 'Proprietary Rights, Trademarks & Artistic Copyright' },
  { id: 'sec-12', num: '12.0', title: 'User Conduct, Cyber Security & Statutory Prohibitions' },
  { id: 'sec-13', num: '13.0', title: 'Promotional Covenants & Discount Coupon Restrictions' },
  { id: 'sec-14', num: '14.0', title: 'Disclaimer of Warranties & Garment Care Obligations' },
  { id: 'sec-15', num: '15.0', title: 'Limitation of Liability & Liquidated Damages Cap' },
  { id: 'sec-16', num: '16.0', title: 'Indemnification Covenant' },
  { id: 'sec-17', num: '17.0', title: 'Data Protection & Compliance with DPDP Act, 2023' },
  { id: 'sec-18', num: '18.0', title: 'Third-Party Intermediaries & Logistics Providers' },
  { id: 'sec-19', num: '19.0', title: 'Force Majeure Exclusions' },
  { id: 'sec-20', num: '20.0', title: 'Governing Law, Dispute Resolution & Exclusive Jurisdiction' },
  { id: 'sec-21', num: '21.0', title: 'Severability, Entire Agreement & Amendments' },
  { id: 'sec-22', num: '22.0', title: 'Statutory Notice & Grievance Redressal Officer' },
];

export default function TermsPage() {
  return (
    <LegalLayout
      title="Terms & Conditions of Sale and Platform Covenant"
      subtitle="Standard Legal Instrument governing electronic access, made-to-order manufacturing, digital sales, and statutory personal data processing under Indian Law."
      docReference="KLS/LGL/2026-TNC/IND"
      effectiveDate="July 23, 2026"
      lastUpdated="September 27, 2026"
      jurisdiction="Courts of Competent Jurisdiction at Mumbai, Maharashtra, India"
      statutoryActs={[
        'Information Technology Act, 2000 (Act 21 of 2000)',
        'Digital Personal Data Protection Act, 2023 (Act 22 of 2023)',
        'Indian Contract Act, 1872 (Act 9 of 1872)',
        'Consumer Protection (E-Commerce) Rules, 2020',
        'Central Goods and Services Tax Act, 2017',
      ]}
      toc={TOC}
    >
      {/* ── SECTION 1.0 ── */}
      <section id="sec-1" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 1.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            1.0 PRELIMINARY RECITALS &amp; STATUTORY ENFORCEABILITY
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>1.1 Electronic Record:</strong> This legal instrument constitutes an electronic record within
            the meaning of the <em>Information Technology Act, 2000</em>, and rules framed thereunder, as applicable,
            including the amended provisions pertaining to electronic records in various statutes as amended by the
            said Act. This electronic record is generated by a computer system and does not require any physical or
            digital signature to attain full legal enforceability.
          </p>
          <p>
            <strong>1.2 Contracting Parties:</strong> These Terms and Conditions (&ldquo;Terms&rdquo; or
            &ldquo;Covenant&rdquo;) are entered into by and between <strong>KALASTRA</strong>, a sole proprietorship
            domiciled and operating under the laws of the Republic of India (hereinafter referred to as the
            &ldquo;Company&rdquo;, &ldquo;Kalastra&rdquo;, &ldquo;we&rdquo;, &ldquo;us&rdquo;, or &ldquo;our&rdquo;),
            and any natural or legal person who accesses, browses, creates an account on, or purchases products through
            our e-commerce platform (hereinafter referred to as the &ldquo;User&rdquo;, &ldquo;Customer&rdquo;,
            &ldquo;you&rdquo;, or &ldquo;your&rdquo;).
          </p>
          <p>
            <strong>1.3 Unconditional Acceptance:</strong> By accessing the Site or initiating an Order, you
            expressly, knowingly, and irrevocably accept, acknowledge, and agree to be bound by every term, condition,
            obligation, and restriction set forth herein, together with our <strong>Privacy Policy</strong> (formulated
            in strict compliance with the <em>Digital Personal Data Protection Act, 2023</em>), our <strong>Cookie
            Policy</strong>, and our <strong>Cancellation &amp; Refund Policy</strong>. If you do not accept these Terms
            without reservation, you are not permitted to access the Site or procure any goods offered thereon.
          </p>
        </div>
      </section>

      {/* ── SECTION 2.0 ── */}
      <section id="sec-2" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 2.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            2.0 STATUTORY DEFINITIONS &amp; CONSTRUCTION
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            Whenever used in this Covenant, the following capitalized terms shall have the respective meanings
            ascribed below:
          </p>
          <div className="border border-black divide-y divide-black font-mono text-xs my-3 bg-neutral-50">
            <div className="p-3">
              <span className="font-bold text-black uppercase">&ldquo;Business Day&rdquo;:</span> Any day other than a
              Saturday, Sunday, or a public holiday declared by the Central Government of India or the State Government
              of Maharashtra, during which commercial banks in Mumbai are open for regular transaction processing.
            </div>
            <div className="p-3">
              <span className="font-bold text-black uppercase">&ldquo;Data Fiduciary&rdquo;:</span> Has the meaning
              assigned to it under Section 2(i) of the <em>Digital Personal Data Protection Act, 2023 (DPDP Act)</em>,
              referring specifically to Kalastra, which determines the purpose and means of processing personal data.
            </div>
            <div className="p-3">
              <span className="font-bold text-black uppercase">&ldquo;Data Principal&rdquo;:</span> Has the meaning
              assigned to it under Section 2(j) of the <em>DPDP Act, 2023</em>, referring to the natural person to
              whom the personal data relates (the User/Customer).
            </div>
            <div className="p-3">
              <span className="font-bold text-black uppercase">&ldquo;Made-to-Order Goods&rdquo;:</span> Any garment,
              apparel item, or accessory that is not held in pre-existing ready inventory, but is customized, cut,
              tailored, dyed, or stitched specifically pursuant to an individual customer&rsquo;s Order confirmation.
            </div>
            <div className="p-3">
              <span className="font-bold text-black uppercase">&ldquo;Order&rdquo;:</span> A legally binding purchase
              requisition submitted by the User via the Site and acknowledged by Kalastra through electronic confirmation.
            </div>
            <div className="p-3">
              <span className="font-bold text-black uppercase">&ldquo;Site&rdquo;:</span> The online e-commerce website,
              subdomains, progressive web applications, and digital storefronts operated by Kalastra.
            </div>
          </div>
        </div>
      </section>

      {/* ── SECTION 3.0 ── */}
      <section id="sec-3" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 3.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            3.0 ENTITY IDENTIFICATION &amp; REGULATORY STATUS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            Pursuant to Rule 3(2) of the <em>Consumer Protection (E-Commerce) Rules, 2020</em>, the statutory details
            of the operating business entity are declared as under:
          </p>

          {/* ── Mobile Key-Value Card Layout (sm:hidden) ── */}
          <div className="sm:hidden border border-black divide-y divide-neutral-200 bg-neutral-50 font-mono text-xs my-3">
            <div className="p-2.5">
              <span className="text-[9px] uppercase tracking-wider text-neutral-500 block">Trade &amp; Legal Name</span>
              <strong className="text-black text-xs">KALASTRA</strong>
            </div>
            <div className="p-2.5">
              <span className="text-[9px] uppercase tracking-wider text-neutral-500 block">Legal Constitution</span>
              <span className="text-neutral-800 text-xs">Sole Proprietorship (India)</span>
            </div>
            <div className="p-2.5">
              <span className="text-[9px] uppercase tracking-wider text-neutral-500 block">Principal Place of Business</span>
              <span className="text-neutral-800 text-xs">Kopar Railway Station, Mumbai, Maharashtra, India</span>
            </div>
            <div className="p-2.5">
              <span className="text-[9px] uppercase tracking-wider text-neutral-500 block">GSTIN Status</span>
              <span className="text-neutral-800 text-xs">Registered under CGST/SGST Acts (Reflected on invoice)</span>
            </div>
            <div className="p-2.5">
              <span className="text-[9px] uppercase tracking-wider text-neutral-500 block">Official Support Email</span>
              <span className="text-black font-bold text-xs break-all">kalastra29@gmail.com</span>
            </div>
            <div className="p-2.5">
              <span className="text-[9px] uppercase tracking-wider text-neutral-500 block">Direct Telephone Support</span>
              <span className="text-black font-bold text-xs">+91 9082260829 (Mon&ndash;Fri, 10:00 to 18:00 IST)</span>
            </div>
          </div>

          {/* ── Desktop Clean Table View (hidden sm:block) ── */}
          <div className="hidden sm:block overflow-x-auto w-full my-3">
            <table className="w-full border border-black text-xs font-mono">
              <tbody>
                <tr className="border-b border-black bg-neutral-100">
                  <td className="p-2.5 font-bold w-1/3 border-r border-black uppercase">Trade &amp; Legal Name</td>
                  <td className="p-2.5 font-bold">KALASTRA</td>
                </tr>
                <tr className="border-b border-black">
                  <td className="p-2.5 font-bold border-r border-black uppercase">Legal Constitution</td>
                  <td className="p-2.5">Sole Proprietorship established under the laws of India</td>
                </tr>
                <tr className="border-b border-black bg-neutral-50">
                  <td className="p-2.5 font-bold border-r border-black uppercase">Principal Place of Business</td>
                  <td className="p-2.5">Kopar Railway Station, Mumbai, Maharashtra, India</td>
                </tr>
                <tr className="border-b border-black">
                  <td className="p-2.5 font-bold border-r border-black uppercase">GSTIN Status</td>
                  <td className="p-2.5">Registered under CGST/SGST Acts; detailed on purchase invoices</td>
                </tr>
                <tr className="border-b border-black bg-neutral-50">
                  <td className="p-2.5 font-bold border-r border-black uppercase">Official Email</td>
                  <td className="p-2.5 font-bold break-all">kalastra29@gmail.com</td>
                </tr>
                <tr>
                  <td className="p-2.5 font-bold border-r border-black uppercase">Telephonic Support</td>
                  <td className="p-2.5 font-bold">+91 9082260829 (Mon&ndash;Fri, 10:00 to 18:00 IST)</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </section>

      {/* ── SECTION 4.0 ── */}
      <section id="sec-4" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 4.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            4.0 USER ELIGIBILITY, ACCOUNTS &amp; CONTRACTUAL CAPACITY
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>4.1 Competence to Contract:</strong> Pursuant to Section 11 of the <em>Indian Contract Act, 1872</em>,
            use of the Site is available only to persons who can form legally binding contracts under applicable law.
            Persons who are &ldquo;incompetent to contract&rdquo; within the meaning of the Indian Contract Act, 1872,
            including un-discharged insolvents and minors (individuals who have not completed the age of eighteen (18)
            years), are not eligible to register or order products independently.
          </p>
          <p>
            <strong>4.2 Mandatory Account Creation:</strong> Guest transactions are disabled. Every User must establish
            a registered account by submitting accurate, truthful, and complete personal data. You warrant that all
            representations made regarding identity, age, telephone number, and delivery addresses are authentic.
          </p>
          <p>
            <strong>4.3 Credential Custodianship:</strong> You are solely responsible for maintaining the confidentiality
            of your username, authentication token, and password. Any transaction originating from your authenticated
            credentials shall be deemed lawfully executed by you, and you shall remain strictly liable for all financial
            obligations arising therefrom.
          </p>
        </div>
      </section>

      {/* ── SECTION 5.0 ── */}
      <section id="sec-5" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 5.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            5.0 MADE-TO-ORDER MANUFACTURING DOCTRINE &amp; TOLERANCES
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>5.1 Customized Production:</strong> Kalastra operates on a zero-inventory, made-to-order manufacturing
            model. Every garment is crafted individually only after an Order is confirmed and full prepayment is received.
            Raw fabric allocation, cutting, pattern drafting, and hand-finishing commence immediately upon confirmation.
          </p>
          <p>
            <strong>5.2 Standard Tolerances:</strong> Handcrafted and tailored textiles are subject to natural variations.
            The Customer acknowledges and agrees that:
          </p>
          <ul className="list-disc pl-5 sm:pl-6 space-y-1">
            <li>
              A dimensional measurement variance of <strong>1 to 2 centimeters</strong> along seams, sleeves, or lengths
              is standard industry tolerance and does not constitute a defect or non-conformity.
            </li>
            <li>
              Color rendition may vary between computer/mobile display screens (due to RGB calibration, panel technology,
              and backlighting) and actual dye lots on natural fibers. Such subtle optical variations are not defects.
            </li>
            <li>
              Kalastra manufactures strictly in accordance with its standardized size charts. Custom bespoke sizing,
              fitting alterations, or personal adjustments are not provided.
            </li>
          </ul>
        </div>
      </section>

      {/* ── SECTION 6.0 ── */}
      <section id="sec-6" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 6.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            6.0 ORDER OFFER, ACCEPTANCE &amp; STRICT NO-CANCELLATION COVENANT
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>6.1 Contract Formation:</strong> Placing an Order constitutes an irrevocable offer to purchase the
            specified goods. The contract of sale is concluded and becomes legally binding only when Kalastra issues an
            electronic confirmation email verifying payment receipt.
          </p>
          <div className="border border-black p-3 sm:p-4 bg-neutral-100 font-mono text-xs break-words">
            <strong className="block uppercase text-black mb-1">
              NOTICE OF STRICT NO-CANCELLATION BY CUSTOMER:
            </strong>
            PURSUANT TO THE CUSTOMIZED AND MADE-TO-ORDER NATURE OF KALASTRA APPAREL, ONCE AN ORDER IS PLACED
            AND PAYMENT IS VERIFIED, CANCELLATION BY THE CUSTOMER IS ABSOLUTELY PROHIBITED. RAW MATERIAL COMMITMENTS
            AND ARTISAN CUTTING COMMENCE IMMEDIATELY. NO REFUNDS OR REVERSALS SHALL BE PERMITTED FOR BUYER REMORSE
            OR MISTAKEN ORDERS.
          </div>
          <p>
            <strong>6.2 Cancellation by Company:</strong> Kalastra reserves the right to cancel an Order prior to dispatch
            solely in cases of quality-control rejection, discovery of pricing errors, or suspected fraudulent activity.
            In such events, Kalastra will issue a full 100% refund to the original payment method within 7 to 14 Business
            Days as the customer&rsquo;s sole and exclusive remedy.
          </p>
        </div>
      </section>

      {/* ── SECTION 7.0 ── */}
      <section id="sec-7" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 7.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            7.0 PRICING, CURRENCY (INR) &amp; TAX INVOICING (GST)
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>7.1 Indian Rupees &amp; Taxes:</strong> All prices displayed on the Site are denominated in Indian
            Rupees (INR) and are inclusive of Goods and Services Tax (GST) applicable under the <em>Central Goods and
            Services Tax Act, 2017</em>, and corresponding State/Integrated GST enactments.
          </p>
          <p>
            <strong>7.2 Pricing Rectification:</strong> In the event a product is erroneously listed at an incorrect
            price due to technical error, Kalastra reserves the right to cancel any Order placed at the erroneous price,
            promptly refunding any amounts paid.
          </p>
        </div>
      </section>

      {/* ── SECTION 8.0 ── */}
      <section id="sec-8" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 8.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            8.0 ONLINE PAYMENT PROTOCOLS &amp; NON-RETENTION OF CREDENTIALS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>8.1 Prepayment Requirement:</strong> All Orders must be paid in full prior to the initiation of
            manufacturing. Cash-on-Delivery (COD), offline drafts, and post-dated payments are not accepted.
          </p>
          <p>
            <strong>8.2 Third-Party Payment Aggregator:</strong> All payment transactions are processed exclusively
            through RBI-authorized payment aggregators (including Razorpay Software Private Limited) using 256-bit SSL
            encryption conforming to the <em>Payment Card Industry Data Security Standard (PCI-DSS)</em>.
          </p>
          <p>
            <strong>8.3 Non-Retention of Financial Credentials:</strong> Kalastra does not collect, view, or store
            complete debit/credit card numbers, CVVs, net-banking credentials, or UPI PINs on its servers. All financial
            credentials are tokenized directly by authorized payment gateways.
          </p>
        </div>
      </section>

      {/* ── SECTION 9.0 ── */}
      <section id="sec-9" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 9.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            9.0 DOMESTIC SHIPPING, DELIVERY TIMELINES &amp; RISK ALLOCATION
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>9.1 Territorial Limitation:</strong> Orders are accepted and fulfilled exclusively within the
            sovereign territory of India. We do not dispatch to international destinations.
          </p>
          <p>
            <strong>9.2 Fulfillment Timelines:</strong> Estimated delivery timeline is <strong>7 to 14 Business Days</strong>
            from the date of Order confirmation. This timeframe incorporates custom artisan manufacturing (typically 4–7
            Business Days) followed by domestic courier transit.
          </p>
          <p>
            <strong>9.3 Transit Risk Allocation:</strong> Kalastra bears the risk of loss or destruction of goods while
            in transit until physical delivery at the shipping address provided. If a shipment is confirmed lost by our
            carrier, Kalastra will manufacture a replacement or issue a full refund.
          </p>
          <p>
            <strong>9.4 Accurate Address Obligation:</strong> You are solely responsible for ensuring accuracy of your
            postal PIN code, street address, and contact telephone number. If a parcel is returned undelivered due to an
            incomplete or erroneous address, re-dispatch charges will be billed to the Customer.
          </p>
        </div>
      </section>

      {/* ── SECTION 10.0 ── */}
      <section id="sec-10" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 10.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            10.0 RETURNS, INSPECTION &amp; QUALIFYING DEFECT POLICY
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>10.1 Limited Return Rights:</strong> Given the made-to-order nature of each piece, returns are
            strictly confined to items that are demonstrably defective, damaged during transit, or materially mismatched
            from the confirmed Order.
          </p>
          <p>
            <strong>10.2 Mandatory 7-Day Notice:</strong> Any claim of damage or manufacturing defect must be reported
            within <strong>7 calendar days of physical delivery</strong> by emailing <code>kalastra29@gmail.com</code> with:
          </p>
          <ul className="list-disc pl-5 sm:pl-6 space-y-1 text-xs">
            <li>The official Order Number and invoice copy;</li>
            <li>High-resolution digital photographs and/or unboxing video clearly displaying the alleged defect;</li>
            <li>Photographs of the outer courier packaging and tags.</li>
          </ul>
          <p>
            <strong>10.3 Restitution:</strong> For approved defect claims, Kalastra will provide reverse pickup or a
            prepaid shipping label at its own cost and, following inspection, issue a full refund to the original payment
            source within <strong>7 to 14 Business Days</strong>. Direct exchanges are not offered. Refer to our
            dedicated <strong>Cancellation &amp; Refund Policy</strong> for complete procedural details.
          </p>
        </div>
      </section>

      {/* ── SECTION 11.0 ── */}
      <section id="sec-11" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 11.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            11.0 PROPRIETARY RIGHTS, TRADEMARKS &amp; ARTISTIC COPYRIGHT
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>11.1 Brand Ownership:</strong> All trademarks, service marks, trade names, brand imagery, garment
            designs, graphics, photographs, audio/video assets, and software code embodied within the Site are the exclusive
            intellectual property of Kalastra, protected under the <em>Trade Marks Act, 1999</em>, the <em>Copyright
            Act, 1957</em>, the <em>Designs Act, 2000</em>, and applicable international conventions.
          </p>
          <p>
            <strong>11.2 License Restrictions:</strong> You are granted a limited, revocable, non-exclusive license solely
            for personal, non-commercial viewing of the Site. No portion of our garment designs, artwork, or textual
            content may be scraped, replicated, re-sold, or reverse-engineered without prior written authorization from
            Kalastra.
          </p>
        </div>
      </section>

      {/* ── SECTION 12.0 ── */}
      <section id="sec-12" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 12.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            12.0 USER CONDUCT, CYBER SECURITY &amp; STATUTORY PROHIBITIONS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            In accordance with Rule 3(1)(b) of the <em>Information Technology (Intermediary Guidelines and Digital Media
            Ethics Code) Rules, 2021</em>, you agree not to host, display, upload, modify, transmit, or distribute any
            information that:
          </p>
          <ul className="list-disc pl-5 sm:pl-6 space-y-1 text-xs">
            <li>Belongs to another person and to which you do not have any legal right;</li>
            <li>Is defamatory, obscene, pornographic, pedophilic, invasive of another&rsquo;s privacy, or racially offensive;</li>
            <li>Infringes any patent, trademark, copyright, or other proprietary rights;</li>
            <li>Contains software viruses or any malicious computer code designed to disrupt, destroy, or limit the functionality of any computer resource;</li>
            <li>Threatens the unity, integrity, defense, security, or sovereignty of India, or public order.</li>
          </ul>
        </div>
      </section>

      {/* ── SECTION 13.0 ── */}
      <section id="sec-13" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 13.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            13.0 PROMOTIONAL COVENANTS &amp; DISCOUNT COUPON RESTRICTIONS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            Discount codes and promotional credits issued by Kalastra are non-transferable, possess no cash surrender
            value, and cannot be combined unless expressly stated in the promotion terms. Kalastra reserves the absolute
            right to revoke any promotional coupon in the event of suspected abuse or unauthorized distribution.
          </p>
        </div>
      </section>

      {/* ── SECTION 14.0 ── */}
      <section id="sec-14" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 14.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            14.0 DISCLAIMER OF WARRANTIES &amp; GARMENT CARE OBLIGATIONS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>14.1 As-Is Standard:</strong> Except as expressly provided herein or required by mandatory Indian
            consumer protection statutes, the Site, services, and apparel are supplied on an &ldquo;as is&rdquo; and
            &ldquo;as available&rdquo; basis without warranties of any kind, whether express or implied.
          </p>
          <p>
            <strong>14.2 Garment Care:</strong> Customers must scrupulously adhere to wash and care instructions affixed
            to garments. Kalastra disclaims all liability for color bleeding, fabric degradation, shrinkage, or distortion
            resulting from machine-washing, harsh detergents, or non-recommended dry cleaning.
          </p>
        </div>
      </section>

      {/* ── SECTION 15.0 ── */}
      <section id="sec-15" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 15.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            15.0 LIMITATION OF LIABILITY &amp; LIQUIDATED DAMAGES CAP
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            To the maximum extent permissible under applicable Indian law, Kalastra, its sole proprietor, and its
            representatives shall not be liable for any indirect, incidental, punitive, special, or consequential damages
            arising out of or in connection with the purchase of goods or utilization of the platform.
          </p>
          <p className="border border-black p-3 bg-neutral-50 font-mono text-xs break-words">
            <strong>AGGREGATE MAXIMUM LIABILITY:</strong> IN NO EVENT SHALL THE TOTAL CUMULATIVE LIABILITY OF KALASTRA
            FOR ALL CLAIMS ARISING OUT OF AN ORDER EXCEED THE EXACT PURCHASE PRICE ACTUALLY PAID BY THE CUSTOMER FOR
            THE SPECIFIC GARMENT GIVING RISE TO THE ALLEGED CAUSE OF ACTION.
          </p>
        </div>
      </section>

      {/* ── SECTION 16.0 ── */}
      <section id="sec-16" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 16.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            16.0 INDEMNIFICATION COVENANT
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            You agree to defend, indemnify, and hold harmless Kalastra, its proprietor, affiliates, and contractors
            from and against any claims, liabilities, damages, losses, costs, and expenses (including reasonable legal fees)
            arising from: (a) your breach of these Terms; (b) your violation of any third-party rights, including IP or privacy
            rights; or (c) any fraud, misrepresentation, or gross negligence committed by you.
          </p>
        </div>
      </section>

      {/* ── SECTION 17.0 (DPDP ACT 2023 COMPLIANCE) ── */}
      <section id="sec-17" className="border-b border-black pb-6 sm:pb-8 bg-neutral-50 p-3 sm:p-4 border">
        <div className="border-b border-black pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-black mb-1">
            STATUTORY CLAUSE 17.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            17.0 DATA PROTECTION &amp; COMPLIANCE WITH DPDP ACT, 2023
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>17.1 Statutory Recognition:</strong> Kalastra recognizes and strictly complies with the provisions of
            the <em>Digital Personal Data Protection Act, 2023 (Act No. 22 of 2023)</em> of the Parliament of India
            (&ldquo;DPDP Act&rdquo;), the <em>Information Technology Act, 2000</em>, and the <em>Information Technology
            (Reasonable Security Practices and Procedures and Sensitive Personal Data or Information) Rules, 2011</em>.
          </p>
          <p>
            <strong>17.2 Legal Capacities:</strong> In all processing of digital personal data:
          </p>
          <ul className="list-disc pl-5 sm:pl-6 space-y-1 text-xs">
            <li>
              <strong>Kalastra</strong> acts strictly as a <strong>&ldquo;Data Fiduciary&rdquo;</strong> as defined under
              Section 2(i) of the DPDP Act, determining the purpose and means of data processing;
            </li>
            <li>
              <strong>The Customer/User</strong> is designated as the <strong>&ldquo;Data Principal&rdquo;</strong> as
              defined under Section 2(j) of the DPDP Act.
            </li>
          </ul>
          <p>
            <strong>17.3 Lawful Grounds for Processing:</strong> Personal data (including name, delivery address, phone
            number, email, and billing records) is processed solely for lawful purposes under Section 4 and Section 6
            of the DPDP Act, specifically:
          </p>
          <ul className="list-disc pl-5 sm:pl-6 space-y-1 text-xs">
            <li>To fulfill the contractual made-to-order manufacturing and delivery covenant agreed upon by you;</li>
            <li>To comply with statutory invoicing and tax filing obligations under the Central Goods and Services Tax Act, 2017;</li>
            <li>To render transactional status updates, shipping tracking, and customer grievance resolution;</li>
            <li>Pursuant to specified lawful consents explicitly provided during registration or checkout.</li>
          </ul>
          <p>
            <strong>17.4 Statutory Rights of Data Principals:</strong> Under Sections 11, 12, 13, and 14 of the DPDP Act,
            2023, you enjoy statutory rights including:
          </p>
          <ul className="list-disc pl-5 sm:pl-6 space-y-1 text-xs">
            <li><strong>Right to Access Information:</strong> Obtain a summary of your personal data processed by Kalastra;</li>
            <li><strong>Right to Correction &amp; Erasure:</strong> Request correction of inaccurate data, completion of incomplete records, or erasure of data no longer necessary for tax or fulfillment purposes;</li>
            <li><strong>Right of Grievance Redressal:</strong> File grievances directly with our statutory Grievance Redressal Officer;</li>
            <li><strong>Right to Nominate:</strong> Nominate another individual to exercise your rights in the event of death or incapacity.</li>
          </ul>
          <p>
            <strong>17.5 Processing of Children&rsquo;s Personal Data:</strong> In accordance with Section 9 of the DPDP Act,
            Kalastra does not knowingly process personal data of children under eighteen (18) years of age without verifiable
            parental consent, nor does it engage in tracking, behavioral monitoring, or targeted advertising directed at children.
          </p>
          <p>
            <strong>17.6 Data Protection Board of India (DPBI):</strong> In the event any grievance is not resolved to your
            satisfaction through our internal redressal mechanism within the statutory timeframe, you hold the legal right
            to lodge a formal complaint before the <strong>Data Protection Board of India</strong> as constituted under
            Section 18 of the DPDP Act, 2023.
          </p>
          <p className="text-xs italic text-neutral-600">
            For exhaustive details on data categories, retention schedules, and international transfer restrictions, refer to
            our standalone <strong>Privacy Policy (DPDP Act, 2023 Compliant)</strong>.
          </p>
        </div>
      </section>

      {/* ── SECTION 18.0 ── */}
      <section id="sec-18" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 18.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            18.0 THIRD-PARTY INTERMEDIARIES &amp; LOGISTICS PROVIDERS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            Order fulfillment requires engagement of licensed third-party logistics carriers and certified payment
            gateways (Data Processors under the DPDP Act). While Kalastra ensures such partners adhere to stringent
            confidentiality and data protection standards, Kalastra is not liable for autonomous courier operational delays
            caused by regional weather, strikes, or regional transport curfews.
          </p>
        </div>
      </section>

      {/* ── SECTION 19.0 ── */}
      <section id="sec-19" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 19.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            19.0 FORCE MAJEURE EXCLUSIONS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            Neither party shall be held in breach of this Covenant for delay or failure of performance resulting from acts
            of God, national lockdowns, state epidemics, floods, earthquakes, armed conflicts, civic strife, telecommunications
            failures, electrical grid shutdowns, or governmental embargoes beyond reasonable control. In such events, manufacturing
            and delivery milestones shall be extended by a duration equivalent to the period of disruption.
          </p>
        </div>
      </section>

      {/* ── SECTION 20.0 ── */}
      <section id="sec-20" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 20.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            20.0 GOVERNING LAW, DISPUTE RESOLUTION &amp; EXCLUSIVE JURISDICTION
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>20.1 Governing Law:</strong> These Terms and any dispute or claim arising out of or in connection with
            them shall be governed by, construed, and enforced in accordance with the substantive laws of the Republic
            of India, without regard to conflict of law principles.
          </p>
          <p>
            <strong>20.2 Good-Faith Conciliation:</strong> Prior to initiating any formal legal suit, the aggrieved party
            shall transmit a formal written Statement of Dispute to the other party, allowing thirty (30) days for informal
            good-faith resolution.
          </p>
          <p className="border border-black p-3 bg-neutral-50 font-mono text-xs break-words">
            <strong>EXCLUSIVE TERRITORIAL JURISDICTION:</strong> SUBJECT TO MANDATORY PROVISIONS OF APPLICABLE CONSUMER
            PROTECTION LAWS, ALL DISPUTES, LITIGATION, OR LEGAL PROCEEDINGS ARISING FROM OR PERTAINING TO THIS COVENANT
            SHALL BE SUBJECT TO THE SOLE AND EXCLUSIVE JURISDICTION OF THE COURTS OF COMPETENT JURISDICTION SITUATED AT
            <strong> MUMBAI, MAHARASHTRA, INDIA</strong>.
          </p>
        </div>
      </section>

      {/* ── SECTION 21.0 ── */}
      <section id="sec-21" className="border-b border-black pb-6 sm:pb-8">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 21.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            21.0 SEVERABILITY, ENTIRE AGREEMENT &amp; AMENDMENTS
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            <strong>21.1 Severability:</strong> If any provision of these Terms is adjudicated to be unlawful, void, or
            unenforceable by a competent court or tribunal, such provision shall be deemed severable and shall not affect
            the validity and enforceability of any remaining provisions.
          </p>
          <p>
            <strong>21.2 Entire Understanding:</strong> These Terms, together with the Privacy Policy, Cookie Policy,
            and individual Order Confirmations, constitute the entire legal covenant between Kalastra and the User,
            superseding all prior electronic, oral, or written communications.
          </p>
          <p>
            <strong>21.3 Unilateral Amendments:</strong> Kalastra reserves the right to amend these Terms to reflect legislative
            changes (including notifications under the DPDP Act, 2023). Notice of material changes will be displayed on this
            page with an updated revision date.
          </p>
        </div>
      </section>

      {/* ── SECTION 22.0 ── */}
      <section id="sec-22" className="pb-4">
        <div className="border-b border-neutral-300 pb-2 mb-3 sm:mb-4">
          <div className="text-[10px] sm:text-xs font-mono font-bold uppercase tracking-widest text-neutral-500 mb-1">
            CLAUSE 22.0
          </div>
          <h2 className="text-base sm:text-lg font-serif font-black uppercase text-black leading-snug break-words">
            22.0 STATUTORY NOTICE &amp; GRIEVANCE REDRESSAL OFFICER
          </h2>
        </div>
        <div className="space-y-3">
          <p>
            Pursuant to Rule 5(9) of the <em>Consumer Protection (E-Commerce) Rules, 2020</em> and Section 13 of the
            <em>Digital Personal Data Protection Act, 2023</em>, the contact particulars of our statutory Grievance
            Redressal Officer are as follows:
          </p>
          <div className="border border-black p-3 sm:p-4 bg-neutral-50 font-mono text-xs space-y-1 break-words">
            <div className="font-bold text-sm text-black">GRIEVANCE REDRESSAL &amp; DATA PROTECTION DESK</div>
            <div><strong>Designated Officer:</strong> Legal Compliance Lead &amp; Grievance Officer</div>
            <div><strong>Entity:</strong> Kalastra (Sole Proprietorship)</div>
            <div><strong>Postal Address:</strong> Kopar Railway Station, Mumbai, Maharashtra, India</div>
            <div><strong>Grievance Email:</strong> <span className="break-all">kalastra29@gmail.com</span></div>
            <div><strong>Direct Telephone:</strong> +91 9082260829</div>
            <div><strong>Statutory Acknowledgment Window:</strong> Within 48 hours of receipt</div>
            <div><strong>Resolution Redressal Timeline:</strong> Within 30 days of registration</div>
          </div>
        </div>
      </section>
    </LegalLayout>
  );
}
